url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lars Rohwedder" # the name of your site, e.g. ACME Corp.
google-scholar: "https://scholar.google.de/citations?hl=en&user=CPVBn8AAAAAJ"
dblp: "https://dblp.org/pers/r/Rohwedder:Lars.html"
email: "contact at larsrohwedder dot com"
phone: "+41 21 693 5219"
address: >
  EPFL </br>
  INJ 131 (Bâtiment INJ) </br>
  Station 14 </br>
  CH-1015 Lausanne
