- from: Apr. 2015 
  to: Jun. 2015 
  title: Research Assistant
  institute: VMWare (Palo Alto, USA)
- from: Feb. 2014 
  to: Apr. 2014
  title: Research Assistant
  institute: Oracle Labs (Redwood Shores, USA)
- from: Mar. 2013 
  to: Sep. 2013
  title: Research Assistant
  institute: Oracle Labs (Redwood Shores, USA)
