- from: 04/2015 
  to: 05/2015 
  title: Research Assistant
  institute: VMWare (Palo Alto, USA)
- from: 02/2014 
  to: 04/2014
  title: Research Assistant
  institute: Oracle Labs (Redwood Shores, USA)
- from: 03/2013 
  to: 09/2013
  title: Research Assistant
  institute: Oracle Labs (Redwood Shores, USA)
